version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Copy build artifacts
          command: |
            mkdir -p ~/artifacts
            cp -R out/* ~/artifacts
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

  deploy:
    docker:
      - image: cimg/aws:2023.12
    steps:
      - checkout
      - attach_workspace:
          at: ~/artifacts

      - run:
          name: Assume deploy role
          command: |
            CREDS_JSON=$(aws sts assume-role \
              --role-arn arn:aws:iam::915920435036:role/circleci-deploy-role \
              --role-session-name circleci-session)

            echo "export AWS_ACCESS_KEY_ID=$(echo $CREDS_JSON | jq -r .Credentials.AccessKeyId)" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$(echo $CREDS_JSON | jq -r .Credentials.SecretAccessKey)" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=$(echo $CREDS_JSON | jq -r .Credentials.SessionToken)" >> $BASH_ENV

            echo "🪪 Role assumed and environment prepared"

      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ~/artifacts s3://circleci-bucket-x/ --delete --region eu-north-1


workflows:
  build-and-deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
