version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  build-jekyll:
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout

      - run:
          name: Init submodules
          command: git submodule update --init --recursive

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Ruby gems
          command: bundle install

      - run:
          name: Build Jekyll site
          command: bundle exec jekyll build

      - run:
          name: Copy build artifacts
          command: |
            mkdir -p ~/artifacts
            cp -R _site/* ~/artifacts

      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - .

  deploy:
    docker:
      - image: node:20
    steps:
      - attach_workspace:
          at: ~/artifacts
      - run:
          name: Install wrangler
          command: npm install -g wrangler
      - run:
          name: Deploy to Cloudflare Pages
          command: |
            wrangler pages deploy ~/artifacts \
              --project-name=my-new-static-site \
              --commit-dirty=true

workflows:
  build-and-deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
